=== pmeisen/dis-timeintervaldataanalyzer/src/net/meisen/dissertation/config/xsd/tidaDimension.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns="http://dev.meisen.net/xsd/dissertation/dimension" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:types="http://dev.meisen.net/xsd/dissertation/types"
           targetNamespace="http://dev.meisen.net/xsd/dissertation/dimension" attributeFormDefault="unqualified" elementFormDefault="qualified">

  <xs:import namespace="http://dev.meisen.net/xsd/dissertation/types" schemaLocation="http://dev.meisen.net/xsd/dissertation/tidaTypes.xsd" />

  <xs:simpleType name="rollUpList">
    <xs:restriction base="xs:string">
      <xs:pattern value="\s*(\*|[A-Za-z][A-Za-z0-9_\-]*)\s*(,\s*(\*|[A-Za-z][A-Za-z0-9_\-]*)\s*)?" />
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="dimensions">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="dimension" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
            
              <xs:element name="hierarchy" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                
                  <xs:sequence>
                    <xs:element name="level" minOccurs="1" maxOccurs="unbounded">
                      <xs:complexType>
                      
                        <xs:sequence>
                          <xs:element name="member" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="id" type="types:identifier" use="required" />
                              <xs:attribute name="name" type="types:nonEmptyString" use="optional" />
                              <xs:attribute name="rollUpTo" type="rollUpList" use="required" />
                              <xs:attribute name="reg" type="xs:string" use="optional" />
                              <xs:attribute name="value" type="xs:string" use="optional" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      
                        <xs:attribute name="id" type="types:identifier" use="required" />
                        <xs:attribute name="name" type="types:nonEmptyString" use="optional" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  
                  <xs:attribute name="id" type="types:identifier" use="required" />
                  <xs:attribute name="name" type="types:nonEmptyString" use="optional" />
                  <xs:attribute name="all" type="types:nonEmptyString" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            
            <xs:attribute name="id" type="types:identifier" use="required" />
            <xs:attribute name="name" type="types:nonEmptyString" use="optional" />
            <xs:attribute name="descriptor" type="types:identifier" use="required" />
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== pmeisen/dis-timeintervaldataanalyzer/test/net/meisen/dissertation/model/dimensions/config/DIMLOC.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<dimensions xmlns="http://dev.meisen.net/xsd/dissertation/dimension"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            
            xsi:schemaLocation="http://dev.meisen.net/xsd/dissertation/dimension  http://dev.meisen.net/xsd/dissertation/tidaDimension.xsd">

  <dimension id="DIMLOC" descriptor="LOC">
    <hierarchy id="LOC" all="All Locations">
      <level id="HOTEL">
        <member id="DREAM" name="Traum" rollUpTo="*" />
        <member id="STAR" rollUpTo="*" />
        <member id="ADV" reg="TENT\d" rollUpTo="*" />
        <member id="TENT" value="TENT" rollUpTo="*" />
      </level>
      <level id="ROOMS" name="RÃ¤ume">
        <member id="POSF" reg="POS F\d" rollUpTo="   DREAM   " />
        <member id="POSG" reg="POS G\d" rollUpTo="  DREAM   , STAR  " />
        <member id="POSA" reg="POS A\d" rollUpTo="STAR" />
      </level>
    </hierarchy>
    <hierarchy id="GEO" name="Geo">
      <level id="COUNTRY">
        <member id="COUNTRYSEL" reg=".*" rollUpTo="*" />
      </level>
    </hierarchy>
  </dimension>
</dimensions>

=== pmeisen/dis-timeintervaldataanalyzer/test/net/meisen/dissertation/model/dimensions/config/DIMMULTIPLEHIERARCHIES.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<dimensions xmlns="http://dev.meisen.net/xsd/dissertation/dimension"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            
            xsi:schemaLocation="http://dev.meisen.net/xsd/dissertation/dimension  http://dev.meisen.net/xsd/dissertation/tidaDimension.xsd">
  
  <timedimension id="MultipleHierarchies">
    <hierarchy id="TIME1">
      <level id="DAY" template="DAYS" />
      <level id="HOUR" template="HOURS" />
      <level id="MINUTE" template="MINUTES" />
    </hierarchy>
    <hierarchy id="TIME2" all="My Name is changed" timezone="America/Chicago">
      <level id="YEAR" template="YEARS" />
      <level id="MONTH" template="MONTHS" />
      <level id="DAY" template="DAYS" />
      <level id="HOUR" name="Hours" template="HOURS" />
      <level id="MINUTE" template="MINUTES" />
    </hierarchy>
  </timedimension>
</dimensions>
